name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1        
    - name: FTP Deploy (incremental)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.HOST }} 
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        local-dir: "./"
        server-dir: "presentesdmais/"