name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: FTP Deploy (incremental)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        ftp-server: ${{ secrets.HOST }} 
        ftp-username: ${{ secrets.USER }}
        ftp-password: ${{ secrets.PASS }}
        localDir: "."
        remoteDir: "public_html/demonstracao"